<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>click the circles. to the beat.</Description>
    <Authors>Morasooma contributors, GooGuTeam, ppy Pty Ltd</Authors>
    <Copyright>Copyright (c) 2026 Morasooma contributors and GooGuTeam. Upstream portions copyright (c) ppy Pty Ltd.</Copyright>
    <PackageProjectUrl>https://github.com/GooGuTeam/osu</PackageProjectUrl>
    <RepositoryUrl>https://github.com/GooGuTeam/osu</RepositoryUrl>
    <PackageReleaseNotes>Morasooma Standard ruleset, based on the upstream osu! ruleset and modified by GooGuTeam.
Upstream copyright: Copyright (c) 2026 ppy Pty Ltd
Full license text: see LICENSE file</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
    <Title>Morasooma Standard ruleset</Title>
    <PackageId>g0v0.osu.Game.Rulesets.Osu</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\osu.Game\osu.Game.csproj" />
  </ItemGroup>
</Project>
